# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_pic', models.ImageField(blank=True, upload_to='stores/', verbose_name='logo/picture')),
                ('store_name', models.CharField(max_length=30, verbose_name='store')),
                ('store_location', models.CharField(max_length=30, verbose_name='location name')),
                ('store_address', models.CharField(max_length=200, verbose_name='Address')),
                ('store_city', models.CharField(max_length=30, verbose_name='city')),
            ],
            options={
                'ordering': ['store_name', 'store_city', 'store_location'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=60, null=True, verbose_name='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_pic',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='product picture'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=0, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_store',
            field=models.ManyToManyField(to='getapp.Store', verbose_name='availability(ies) in store(s)'),
        ),
    ]
