# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_pic', models.ImageField(blank=True, upload_to='products/', verbose_name='product picture')),
                ('product_name', models.CharField(max_length=60, verbose_name='product')),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='price')),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
    ]
