# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getapp', '0003_product_product_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=0, verbose_name='price'),
        ),
    ]
